FROM node:10.21-buster

WORKDIR /opt/geoperil-frontend

VOLUME [ "/opt/geoperil-frontend" ]

RUN apt-get update && \
    apt-get install -y yarn

COPY start-dev.sh /start-dev.sh

EXPOSE 3000

CMD [ "/start-dev.sh" ]
