# GeoPeril - A platform for the computation and web-mapping of hazard specific
# geospatial data, as well as for serving functionality to handle, share, and
# communicate threat specific information in a collaborative environment.
#
# Copyright (C) 2021 GFZ German Research Centre for Geosciences
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.
#
# Contributors:
#   Johannes Spazier (GFZ)
#   Sven Reissland (GFZ)
#   Martin Hammitzsch (GFZ)
#   Matthias Rüster (GFZ)
#   Hannes Fuchs (GFZ)

version: '3.7'

services:
  easywave-worker-global-grid-datasets:
    image: git.gfz-potsdam.de:5000/id2/geoperil/global-grid-datasets:20210323
    container_name: easywave-worker-global-grid-datasets
    volumes:
      - easywave-worker-grid-data-volume:/data

  easywave-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: easywave-worker-cpu
    container_name: easywave-worker-cpu
    environment:
      - DEVELOPMENT=1
      - SERVER_URL=http://localhost:5000/wps
      - OUTPUT_URL=http://localhost:5000/outputs/
    ports:
      - 5000:5000
    volumes:
      - ./wps:/srv/wps
      - easywave-worker-grid-data-volume:/data
    depends_on:
      - easywave-worker-global-grid-datasets

volumes:
  easywave-worker-grid-data-volume:
