# GeoPeril - A platform for the computation and web-mapping of hazard specific
# geospatial data, as well as for serving functionality to handle, share, and
# communicate threat specific information in a collaborative environment.

# Copyright (C) 2021 GFZ German Research Centre for Geosciences

# SPDX-License-Identifier: Apache-2.0

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.

# Contributors:
#   Johannes Spazier (GFZ)
#   Sven Reissland (GFZ)
#   Martin Hammitzsch (GFZ)
#   Matthias Rüster (GFZ)
#   Hannes Fuchs (GFZ)

FROM python:3.7-buster

ARG COMMIT_SHA=439766dce11d795eead531151319bf7e332d8582
ARG DOWNLOAD_URL=https://git.gfz-potsdam.de/api/v4/projects/263/repository/archive.tar.gz?sha=$COMMIT_SHA

WORKDIR /root

RUN wget "$DOWNLOAD_URL" -O easywave.tar.gz && \
    tar xf easywave.tar.gz && \
    rm easywave.tar.gz

RUN apt-get update && \
    apt-get install -y \
        autoconf \
        g++ \
        binutils \
        make \
        gdal-bin \
        python-gdal

RUN cd easyWave-$COMMIT_SHA-$COMMIT_SHA/code && \
    /bin/sh ./bootstrap.sh && \
    ./configure --prefix=/usr && \
    make && \
    make install && \
    which easywave

# for debugging purposes: get version of easywave
RUN easywave --help || true

COPY wps/requirements.txt .

RUN pip3 install -r requirements.txt

WORKDIR /srv/wps
VOLUME [ "/srv/wps", "/data" ]

EXPOSE 5000

CMD [ "/usr/local/bin/python3.7", "/srv/wps/wps.py" ]
