FROM python:3.7-buster

ARG COMMIT_SHA=439766dce11d795eead531151319bf7e332d8582
ARG DOWNLOAD_URL=https://gitext.gfz-potsdam.de/api/v4/projects/263/repository/archive.tar.gz?sha=$COMMIT_SHA

WORKDIR /root

RUN wget "$DOWNLOAD_URL" -O easywave.tar.gz && \
    tar xf easywave.tar.gz && \
    rm easywave.tar.gz

RUN apt-get update && \
    apt-get install -y \
        autoconf \
        g++ \
        binutils \
        make \
        gdal-bin \
        python-gdal

RUN cd easyWave-$COMMIT_SHA-$COMMIT_SHA/code && \
    /bin/sh ./bootstrap.sh && \
    ./configure --prefix=/usr && \
    make && \
    make install && \
    which easywave

# for debugging purposes: get version of easywave
RUN easywave --help || true

COPY wps/requirements.txt .

RUN pip3 install -r requirements.txt

WORKDIR /srv/wps
VOLUME [ "/srv/wps", "/data" ]

EXPOSE 5000

CMD ["/usr/local/bin/python3.7", "wps.py" ]
