version: '3.6'

services:
  mongo:
    image: mongo:3.6.12
    container_name: geoperil-mongo
    volumes:
      - 'mongo-data-volume:/data/db'

  mongo-data:
    image: geoperil-mongodb-data
    build:
      context: ./mongodb-data
      dockerfile: Dockerfile
    container_name: geoperil-mongodb-data
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./mongodb-data/example-data:/tmp/example-data
    command: ["/tmp/scripts/wait-for-mongodb.sh", "/tmp/scripts/import-example-data.sh"]
    environment:
      - MONGO_HOST=mongo
      - MONGO_DB=geoperil

  geoperil-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: geoperil-server
    container_name: geoperil-server
    ports:
      - '8080:80'
    depends_on:
      - mongo
      - worker-easywavecpu
    links:
      - 'worker-easywavecpu:worker'
      - 'mongo'
    volumes:
      - server-tmp-data-volume:/tmp/geoperil
      - ./wsgi:/var/www/geoperil/wsgi
      - ./www:/var/www/geoperil/htdocs
      - ../tools:/opt/geoperil/tools
      - ../worker:/opt/geoperil/worker
      - ../GMT:/opt/geoperil/GMT

  global-grid-datasets:
    image: gitext.gfz-potsdam.de:5000/geoperil/global-grid-datasets:20200526
    container_name: geoperil-grids
    volumes:
      - grid-data-volume:/data

  worker-easywavecpu:
    build:
      context: ../worker
      dockerfile: Dockerfile.easywaveCPU
    image: geoperil-worker
    container_name: geoperil-worker
    volumes:
      - grid-data-volume:/data
    depends_on:
      - global-grid-datasets

volumes:
  server-tmp-data-volume:
  mongo-data-volume:
  grid-data-volume:
