# GeoPeril - A platform for the computation and web-mapping of hazard specific
# geospatial data, as well as for serving functionality to handle, share, and
# communicate threat specific information in a collaborative environment.
#
# Copyright (C) 2021 GFZ German Research Centre for Geosciences
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.
#
# Contributors:
#   Johannes Spazier (GFZ)
#   Sven Reissland (GFZ)
#   Martin Hammitzsch (GFZ)
#   Matthias Rüster (GFZ)
#   Hannes Fuchs (GFZ)

exclude:
  - '.*\.gitlab-ci.yml$'
  - 'meta/.*'

manual dependency config:
  Python:
    - import name: 'base'
      pkg name: 'base'
      ignore: True
    - import name: 'basesrv'
      pkg name: 'basesrv'
      ignore: True
    - import name: 'msgsrv'
      pkg name: 'msgsrv'
      ignore: True
    - import name: 'processes'
      pkg name: 'processes'
      ignore: True
    - import name: 'surfer'
      pkg name: 'surfer'
      ignore: True
    - import name: 'data_products'
      pkg name: 'data_products'
      ignore: True
    - import name: 'auto_extent'
      pkg name: 'auto_extent'
      ignore: True
    - import name: 'build_cpt_file'
      pkg name: 'build_cpt_file'
      ignore: True
    - import name: 'build_legend'
      pkg name: 'build_legend'
      ignore: True
    - import name: 'tsunami_config'
      pkg name: 'tsunami_config'
      ignore: True
    - import name: 'bson'
      pkg name: 'pymongo'
    - import name: 'jsonschema'
      pkg name: 'jsonschema'
      licenses:
        - 'MIT'
    - import name: 'zipp'
      pkg name: 'zipp'
      licenses:
        - 'MIT'
